### PR TITLE
Added KML format, plus other changes

### PR DESCRIPTION
**Pull request by ZiglioUK**
- KML Format
- other changes: added some options, made the display layer permanent, added popup removal (it should fix some corner cases).
  I hope the coding style is alright, have been using a crappy editor for a while

### CODE REVIEW

**Comment by volpino** [comment]
sounds cool :D

**Comment by volpino** [comment]
Ok i took some time to revise your pull request.
Most of it it's really cool, but i fixed some things that i didn't like:
I removed your fix for destroying popups because it is quite annoying if the user is looking at the animated page and clicks on a feature. The popups disappears after less than a second! I didn't manage to figure out an efficient solution that removes popups but reopens them if the point is still there (e.g.: useful in cumulative visualization). I tried to save the position of the selected feature in order to reopen the popup but it's not possible in openlayers to select a feature by position. One solution could be looping on the whole bunch of features but it's really inefficient. Do you have ideas on how to solve this issue?

Notes on code style:
- don't mix tabs and spaces for indentation, it's really awful
- use appropriate spaces no: if(condition) - yes: if (condition) (it's not a function)
- don't use one line if without brackets {} (it happens to add a second line and generate bugs)
- i used this standard for names: MyClass, myMethod, my_attribute. please use it everywhere (or we can change it everywhere, but it must be consistent)

**Comment by ZiglioUK** [comment]
Thanks for time you took reviewing my changes. 
I'll have to think about how to handle popus. But do you agree that that situation might occur, when popups are left behind without no ways to close them? It could be a bug in openlayers.

Sorry about the coding style.... as you've probably guessed I spent most of my time as a java developer and I don't work with anybody else so my coding style is pretty consistent :-)
The problem with mixing tabs and spaces is that the Java editor for Eclipse converts tabs to spaces. Unfortunately the Aptana 2 editor I used at the beginning didn't do that. Once I realized that I switched to the Eclipse built-in javascript editor hoping that that would do the conversion. When I see that tabs are still there I go and change them to spaces by hand.
It would be good to have a better javascript editor for Eclipse though.
I think from now on I'll use more and more jsfiddle, that has got jlint integrated.

**Comment by volpino** [comment]
Yes, the problem occurs but only with your changes for visualizing details of only one point (don't know why! it's openlayer's fault i think). For cluster popups i don't have the issue (a part from the fact that there might be a popup without feature, but it still closes).
We must fix it, a temporary workaround could be to insert your fix but pause the animation when a feature is clicked.

**Comment by ZiglioUK** [comment]
I see the problem during animations. Well, it's due to the fact that popups are child objects of features and features are destroyed and recreated all the time during the animation. If popups are still there with no feature, that's a proof that something is wrong with the way openlayers handle popups (in my view). I'll see if anyone has pointed that out.
So, if openlayers destroyed popups automatically when their parent feature is destroyed, you would have that problem of disappearing popups.
Solutions:
1. We could prevent users from clicking on features during animations.
2. We could look at a way of adding features during animations, rather than destroying them.

Solution 2 is related to what I suggested before about not having to parse formats every time.
One way could be to store all parsed features in one vector and return just the visible ones to be added to the display layer.
Once you do that, for each pass maybe we could avoid destroying features unless they become invisible (because the user pulls back the timeline slider) and we would destroy the popup just for those features that have become invisible.
If you don't destroy the popup once a feature is gone, you would end up with a dangling popup that for example points to the wrong pixel when you zoom in an out.

**Comment by volpino** [comment]
> 2 We could look at a way of adding features during animations, rather than destroying them.

Unfortunately I think it is not possible using cluster strategy :(
Features are re-organized in clusters when the layer is added so it's a complete mess without destroying and recreating everything.
when i wrote that piece of code i looked around but i didn't find anything

**Pull request merged**
